-- Synced from live Supabase migration 20260927204759 (early_game_spells_and_sets)

insert into public.spell_definitions(slug,name,description,enabled,spell_kind,damage_type,mana_cost,required_level,power_multiplier,flat_power,status_effect_type,status_effect_chance,status_effect_turns,status_effect_potency,support_effect_type,support_value,support_turns) values
('weakening_spark','Ослабляющая искра','Быстрый разряд: небольшой электрический урон и 55% шанс Ослабления на 2 хода (-10% исходящего урона).',true,'damage','lightning',12,1,0.75,2,'weaken',55,2,10,null,0,0),
('sand_veil','Песчаная завеса','Защитная завеса вокруг выбранной цели. Следующий входящий удар уменьшается на 55%. Можно накладывать на союзника.',true,'guard',null,15,1,0,0,null,0,0,0,'guard',55,1),
('healing_spark','Целебный импульс','Недорогое раннее лечение. Слабее «Заживления», зато доступно раньше и расходует меньше маны.',true,'heal',null,14,2,0.75,10,null,0,0,0,null,0,0),
('venom_spore','Ядовитая спора','Земляной сгусток спор: небольшой урон и 70% шанс Яда на 3 хода.',true,'damage','earth',15,2,0.8,3,'poison',70,3,5,null,0,0),
('exposing_rune','Руна раскрытия','Арканная руна повреждает защитный рисунок цели и с 70% шансом накладывает Уязвимость на 2 хода.',true,'damage','arcane',18,3,0.7,3,'vulnerable',70,2,12,null,0,0),
('combat_impulse','Боевой импульс','Усиливает следующие 2 прямые атаки на 15%. Работает и с физическими, и с магическими атаками.',true,'buff',null,20,3,0,0,null,0,0,0,'empower',15,2),
('moon_frost','Лунный озноб','Лунный урон и 80% шанс Охлаждения на 2 хода (-18% исходящего урона цели).',true,'damage','moon',22,4,1,6,'chill',80,2,18,null,0,0)
on conflict(slug) do update set name=excluded.name,description=excluded.description,enabled=excluded.enabled,spell_kind=excluded.spell_kind,damage_type=excluded.damage_type,mana_cost=excluded.mana_cost,required_level=excluded.required_level,power_multiplier=excluded.power_multiplier,flat_power=excluded.flat_power,status_effect_type=excluded.status_effect_type,status_effect_chance=excluded.status_effect_chance,status_effect_turns=excluded.status_effect_turns,status_effect_potency=excluded.status_effect_potency,support_effect_type=excluded.support_effect_type,support_value=excluded.support_value,support_turns=excluded.support_turns,updated_at=now();
insert into public.spell_magic_families(spell_id,family_slug) select id,'lightning' from public.spell_definitions where slug='weakening_spark' on conflict do nothing;
insert into public.spell_magic_families(spell_id,family_slug) select id,'control' from public.spell_definitions where slug='weakening_spark' on conflict do nothing;
insert into public.spell_magic_families(spell_id,family_slug) select id,'protective' from public.spell_definitions where slug='sand_veil' on conflict do nothing;
insert into public.spell_magic_families(spell_id,family_slug) select id,'earth' from public.spell_definitions where slug='sand_veil' on conflict do nothing;
insert into public.spell_magic_families(spell_id,family_slug) select id,'healing' from public.spell_definitions where slug='healing_spark' on conflict do nothing;
insert into public.spell_magic_families(spell_id,family_slug) select id,'earth' from public.spell_definitions where slug='venom_spore' on conflict do nothing;
insert into public.spell_magic_families(spell_id,family_slug) select id,'nature' from public.spell_definitions where slug='venom_spore' on conflict do nothing;
insert into public.spell_magic_families(spell_id,family_slug) select id,'arcane' from public.spell_definitions where slug='exposing_rune' on conflict do nothing;
insert into public.spell_magic_families(spell_id,family_slug) select id,'control' from public.spell_definitions where slug='exposing_rune' on conflict do nothing;
insert into public.spell_magic_families(spell_id,family_slug) select id,'enhancement' from public.spell_definitions where slug='combat_impulse' on conflict do nothing;
insert into public.spell_magic_families(spell_id,family_slug) select id,'moon' from public.spell_definitions where slug='moon_frost' on conflict do nothing;
insert into public.spell_magic_families(spell_id,family_slug) select id,'control' from public.spell_definitions where slug='moon_frost' on conflict do nothing;
insert into public.equipment_sets(slug,name,description,total_pieces,enabled) values
('warden_scout','Следопыт Вардена','Лёгкий ранний комплект разведчика: ловкость, удача и уверенная физическая атака.',3,true),
('liaven_apprentice','Ученик Лиавена','Комплект для первых полноценных магических билдов: интеллект, магический урон и возврат маны.',3,true),
('stonewatch','Каменный караул','Тяжёлый комплект стража для раннего танкования и уверенного блока.',4,true),
('ash_circle','Пепельный круг','Редкий комплект боевого мага пустыни. Усиливает заклинания и поддерживает запас маны.',3,true)
on conflict(slug) do update set name=excluded.name,description=excluded.description,total_pieces=excluded.total_pieces,enabled=true,updated_at=now();
insert into public.equipment_set_bonuses(set_id,required_pieces,name,description,effect_type,effect_value,effect_data,sort_order,enabled) select id,2,'Выверенный выпад','2 части: +3% физического прямого урона.','physical_damage_bonus',3,'{}'::jsonb,2,true from public.equipment_sets where slug='warden_scout' on conflict(set_id,required_pieces,effect_type) do update set name=excluded.name,description=excluded.description,effect_value=excluded.effect_value,enabled=true,updated_at=now();
insert into public.equipment_set_bonuses(set_id,required_pieces,name,description,effect_type,effect_value,effect_data,sort_order,enabled) select id,3,'Подвижная защита','3 части: эффективность блока +4 п.п.','guard_boost',4,'{}'::jsonb,3,true from public.equipment_sets where slug='warden_scout' on conflict(set_id,required_pieces,effect_type) do update set name=excluded.name,description=excluded.description,effect_value=excluded.effect_value,enabled=true,updated_at=now();
insert into public.equipment_set_bonuses(set_id,required_pieces,name,description,effect_type,effect_value,effect_data,sort_order,enabled) select id,2,'Связка формул','2 части: +4% магического прямого урона.','magic_damage_bonus',4,'{}'::jsonb,2,true from public.equipment_sets where slug='liaven_apprentice' on conflict(set_id,required_pieces,effect_type) do update set name=excluded.name,description=excluded.description,effect_value=excluded.effect_value,enabled=true,updated_at=now();
insert into public.equipment_set_bonuses(set_id,required_pieces,name,description,effect_type,effect_value,effect_data,sort_order,enabled) select id,3,'Экономная проводимость','3 части: успешная прямая атака восстанавливает 2 маны.','mana_on_hit',2,'{}'::jsonb,3,true from public.equipment_sets where slug='liaven_apprentice' on conflict(set_id,required_pieces,effect_type) do update set name=excluded.name,description=excluded.description,effect_value=excluded.effect_value,enabled=true,updated_at=now();
insert into public.equipment_set_bonuses(set_id,required_pieces,name,description,effect_type,effect_value,effect_data,sort_order,enabled) select id,2,'Каменная стойка','2 части: эффективность блока +5 п.п.','guard_boost',5,'{}'::jsonb,2,true from public.equipment_sets where slug='stonewatch' on conflict(set_id,required_pieces,effect_type) do update set name=excluded.name,description=excluded.description,effect_value=excluded.effect_value,enabled=true,updated_at=now();
insert into public.equipment_set_bonuses(set_id,required_pieces,name,description,effect_type,effect_value,effect_data,sort_order,enabled) select id,4,'Стена караула','4 части: ещё +5 п.п. к эффективности блока.','guard_boost',5,'{}'::jsonb,4,true from public.equipment_sets where slug='stonewatch' on conflict(set_id,required_pieces,effect_type) do update set name=excluded.name,description=excluded.description,effect_value=excluded.effect_value,enabled=true,updated_at=now();
insert into public.equipment_set_bonuses(set_id,required_pieces,name,description,effect_type,effect_value,effect_data,sort_order,enabled) select id,2,'Пепельная формула','2 части: +5% магического прямого урона.','magic_damage_bonus',5,'{}'::jsonb,2,true from public.equipment_sets where slug='ash_circle' on conflict(set_id,required_pieces,effect_type) do update set name=excluded.name,description=excluded.description,effect_value=excluded.effect_value,enabled=true,updated_at=now();
insert into public.equipment_set_bonuses(set_id,required_pieces,name,description,effect_type,effect_value,effect_data,sort_order,enabled) select id,3,'Замкнутый круг','3 части: успешная прямая атака восстанавливает 3 маны.','mana_on_hit',3,'{}'::jsonb,3,true from public.equipment_sets where slug='ash_circle' on conflict(set_id,required_pieces,effect_type) do update set name=excluded.name,description=excluded.description,effect_value=excluded.effect_value,enabled=true,updated_at=now();

