-- Synced from live Supabase migration 20260927204933 (early_game_sets_and_uniques)

insert into public.item_definitions(
slug,name,description,category,rarity,equip_group,stackable,max_stack,stat_modifiers,effects,base_value,
required_level,shop_tier,shop_price,shop_enabled,damage_type,damage_resistances,unique_property_name,
unique_property_description,unique_effect_type,unique_effect_value,damage_bonuses,weapon_base_damage,
weapon_scaling,weapon_family,bow_full_draw_armor_penetration_percent,bloodshed_chance_percent,echo_strike_chance_percent
) values
('warden_scout_hood','Капюшон следопыта Вардена','Часть комплекта ранней игры. Собери несколько частей, чтобы открыть сетовый бонус.','armor','uncommon','head',false,1,'{"agility":2,"luck":1}'::jsonb,'[]'::jsonb,120,2,2,0,false,null,'{"air":4}'::jsonb,null,'',null,0,'{}'::jsonb,0,null,null,0,0,0),
('warden_scout_coat','Куртка следопыта Вардена','Часть комплекта ранней игры. Собери несколько частей, чтобы открыть сетовый бонус.','armor','uncommon','chest',false,1,'{"agility":2,"vitality":1}'::jsonb,'[]'::jsonb,120,2,2,0,false,null,'{"slashing":5,"piercing":5}'::jsonb,null,'',null,0,'{}'::jsonb,0,null,null,0,0,0),
('warden_scout_boots','Сапоги следопыта Вардена','Часть комплекта ранней игры. Собери несколько частей, чтобы открыть сетовый бонус.','armor','uncommon','feet',false,1,'{"agility":2,"luck":1}'::jsonb,'[]'::jsonb,120,2,2,0,false,null,'{"earth":3}'::jsonb,null,'',null,0,'{}'::jsonb,0,null,null,0,0,0),
('liaven_apprentice_hood','Капюшон ученика Лиавена','Часть комплекта ранней игры. Собери несколько частей, чтобы открыть сетовый бонус.','armor','uncommon','head',false,1,'{"intellect":3,"luck":1}'::jsonb,'[]'::jsonb,180,3,3,0,false,null,'{"arcane":4}'::jsonb,null,'',null,0,'{}'::jsonb,0,null,null,0,0,0),
('liaven_apprentice_robe','Мантия ученика Лиавена','Часть комплекта ранней игры. Собери несколько частей, чтобы открыть сетовый бонус.','armor','uncommon','chest',false,1,'{"intellect":3,"vitality":1}'::jsonb,'[]'::jsonb,180,3,3,0,false,null,'{"fire":4,"water":4}'::jsonb,null,'',null,0,'{}'::jsonb,0,null,null,0,0,0),
('liaven_apprentice_charm','Фокус ученика Лиавена','Часть комплекта ранней игры. Собери несколько частей, чтобы открыть сетовый бонус.','accessory','uncommon','accessory',false,1,'{"intellect":2,"luck":2}'::jsonb,'[]'::jsonb,180,3,3,0,false,null,'{"arcane":5}'::jsonb,null,'',null,0,'{}'::jsonb,0,null,null,0,0,0),
('stonewatch_helm','Шлем Каменного караула','Часть комплекта ранней игры. Собери несколько частей, чтобы открыть сетовый бонус.','armor','uncommon','head',false,1,'{"vitality":3}'::jsonb,'[]'::jsonb,180,3,3,0,false,null,'{"blunt":5}'::jsonb,null,'',null,0,'{}'::jsonb,0,null,null,0,0,0),
('stonewatch_cuirass','Кираса Каменного караула','Часть комплекта ранней игры. Собери несколько частей, чтобы открыть сетовый бонус.','armor','rare','chest',false,1,'{"vitality":4,"strength":1}'::jsonb,'[]'::jsonb,180,3,3,0,false,null,'{"blunt":6,"piercing":6,"slashing":6}'::jsonb,null,'',null,0,'{}'::jsonb,0,null,null,0,0,0),
('stonewatch_gauntlets','Латные перчатки Каменного караула','Часть комплекта ранней игры. Собери несколько частей, чтобы открыть сетовый бонус.','armor','uncommon','hands',false,1,'{"strength":2,"vitality":2}'::jsonb,'[]'::jsonb,180,3,3,0,false,null,'{"slashing":4}'::jsonb,null,'',null,0,'{}'::jsonb,0,null,null,0,0,0),
('stonewatch_greaves','Поножи Каменного караула','Часть комплекта ранней игры. Собери несколько частей, чтобы открыть сетовый бонус.','armor','uncommon','legs',false,1,'{"vitality":3,"strength":1}'::jsonb,'[]'::jsonb,180,3,3,0,false,null,'{"piercing":5}'::jsonb,null,'',null,0,'{}'::jsonb,0,null,null,0,0,0),
('ash_circle_hood','Капюшон Пепельного круга','Часть комплекта ранней игры. Собери несколько частей, чтобы открыть сетовый бонус.','armor','rare','head',false,1,'{"intellect":4,"luck":1}'::jsonb,'[]'::jsonb,240,4,4,0,false,null,'{"fire":6,"arcane":4}'::jsonb,null,'',null,0,'{}'::jsonb,0,null,null,0,0,0),
('ash_circle_robe','Одеяние Пепельного круга','Часть комплекта ранней игры. Собери несколько частей, чтобы открыть сетовый бонус.','armor','rare','chest',false,1,'{"intellect":4,"vitality":2}'::jsonb,'[]'::jsonb,240,4,4,0,false,null,'{"fire":8,"arcane":5}'::jsonb,null,'',null,0,'{}'::jsonb,0,null,null,0,0,0),
('ash_circle_focus','Фокус Пепельного круга','Часть комплекта ранней игры. Собери несколько частей, чтобы открыть сетовый бонус.','accessory','rare','accessory',false,1,'{"intellect":3,"luck":2}'::jsonb,'[]'::jsonb,240,4,4,0,false,null,'{"fire":5,"arcane":5}'::jsonb,null,'',null,0,'{}'::jsonb,0,null,null,0,0,0),
('warden_rust_bell','Ржавый колокол Вардена','Старая булава дозорного. Каждый удар возвращает немного жизненной силы.','weapon','unique','weapon',false,1,'{"strength":1,"vitality":1}'::jsonb,'[]'::jsonb,95,1,1,0,false,'blunt','{}'::jsonb,'Глухой звон','3% вампиризма.','lifesteal',3,'{}'::jsonb,7,'strength','mace',0,0,0),
('grey_fox_needle','Игла Серого Лиса','Тонкая рапира неизвестного дуэлянта. Особенно опасна против уже раненой цели.','weapon','unique','weapon',false,1,'{"agility":2,"luck":1}'::jsonb,'[]'::jsonb,190,2,2,0,false,'piercing','{}'::jsonb,'Запах крови','+10% урона по раненым целям.','damage_vs_wounded',10,'{}'::jsonb,7,'agility','rapier',0,0,0),
('liaven_whisper','Шёпот Лиавена','Тонкий жезл, возвращающий часть маны при успешных прямых атаках.','weapon','unique','weapon',false,1,'{"intellect":3,"luck":1}'::jsonb,'[]'::jsonb,190,2,2,0,false,'blunt','{}'::jsonb,'Тихая проводимость','Успешная прямая атака восстанавливает 3 маны.','mana_on_hit',3,'{"arcane":4}'::jsonb,3,'hybrid','wand',0,0,0),
('night_watch_shield','Щит Ночной Стражи','Небольшой щит с удивительно правильным балансом.','armor','unique','offhand',false,1,'{"vitality":3,"luck":1}'::jsonb,'[]'::jsonb,190,2,2,0,false,null,'{"slashing":6,"piercing":6}'::jsonb,'Ночная стойка','+8 п.п. к эффективности блока.','guard_boost',8,'{}'::jsonb,0,null,null,0,0,0),
('quarry_bonebreaker','Костолом Каменоломни','Массивный молот, который становится особенно страшным против уже раненой цели.','weapon','unique','weapon',false,1,'{"strength":3,"vitality":2}'::jsonb,'[]'::jsonb,285,3,3,0,false,'blunt','{}'::jsonb,'Добивание','+12% урона по раненым целям.','damage_vs_wounded',12,'{}'::jsonb,11,'strength','hammer',0,0,0),
('mirage_cloak','Плащ Песчаного Миража','Ткань кажется полупрозрачной в жарком воздухе. Даёт ловкость, удачу и защиту от жара.','armor','unique','chest',false,1,'{"agility":3,"luck":2}'::jsonb,'[]'::jsonb,285,3,3,0,false,null,'{"fire":12,"earth":6,"piercing":4}'::jsonb,null,'',null,0,'{}'::jsonb,0,null,null,0,0,0),
('clay_guardian_heart','Сердце Глиняного Стража','Тяжёлый талисман из обожжённой глины. Помогает удерживать защитную стойку.','accessory','unique','accessory',false,1,'{"vitality":3}'::jsonb,'[]'::jsonb,285,3,3,0,false,null,'{"earth":8,"blunt":5}'::jsonb,'Неподвижность','+7 п.п. к эффективности блока.','guard_boost',7,'{}'::jsonb,0,null,null,0,0,0),
('dry_wind_blade','Клинок Сухого Ветра','Лёгкий меч пустыни. Иногда удар повторяется эхом почти без задержки.','weapon','unique','weapon',false,1,'{"strength":2,"agility":3,"luck":1}'::jsonb,'[]'::jsonb,380,4,4,0,false,'slashing','{}'::jsonb,'Эхо ветра','12% шанс эхо-удара.',null,0,'{"air":4}'::jsonb,11,'hybrid','sword',0,0,12),
('noon_shadow_bow','Лук Полуденной Тени','Короткий лук охотников Сахрета. Серии попаданий способны вызвать Кровопролитие.','weapon','unique','weapon',false,1,'{"agility":4,"luck":2}'::jsonb,'[]'::jsonb,380,4,4,0,false,'piercing','{}'::jsonb,'Красная тетива','8% шанс накапливать Кровопролитие.',null,0,'{}'::jsonb,10,'agility','short_bow',42,8,0),
('seven_spark_staff','Посох Семигранной Искры','Редкий ранний посох, в котором арканная энергия смешана с молнией.','weapon','unique','weapon',false,1,'{"intellect":5,"luck":2}'::jsonb,'[]'::jsonb,380,4,4,0,false,'blunt','{}'::jsonb,'Возврат искры','Успешная прямая атака восстанавливает 4 маны.','mana_on_hit',4,'{"arcane":5,"lightning":5}'::jsonb,5,'hybrid','staff',0,0,0)
on conflict(slug) do update set name=excluded.name,description=excluded.description,category=excluded.category,rarity=excluded.rarity,
equip_group=excluded.equip_group,stat_modifiers=excluded.stat_modifiers,base_value=excluded.base_value,required_level=excluded.required_level,
shop_enabled=false,damage_type=excluded.damage_type,damage_resistances=excluded.damage_resistances,
unique_property_name=excluded.unique_property_name,unique_property_description=excluded.unique_property_description,
unique_effect_type=excluded.unique_effect_type,unique_effect_value=excluded.unique_effect_value,damage_bonuses=excluded.damage_bonuses,
weapon_base_damage=excluded.weapon_base_damage,weapon_scaling=excluded.weapon_scaling,weapon_family=excluded.weapon_family,
bow_full_draw_armor_penetration_percent=excluded.bow_full_draw_armor_penetration_percent,
bloodshed_chance_percent=excluded.bloodshed_chance_percent,echo_strike_chance_percent=excluded.echo_strike_chance_percent,updated_at=now();
update public.item_definitions d set equipment_set_id=s.id,updated_at=now() from public.equipment_sets s where d.slug='warden_scout_hood' and s.slug='warden_scout';
update public.item_definitions d set equipment_set_id=s.id,updated_at=now() from public.equipment_sets s where d.slug='warden_scout_coat' and s.slug='warden_scout';
update public.item_definitions d set equipment_set_id=s.id,updated_at=now() from public.equipment_sets s where d.slug='warden_scout_boots' and s.slug='warden_scout';
update public.item_definitions d set equipment_set_id=s.id,updated_at=now() from public.equipment_sets s where d.slug='liaven_apprentice_hood' and s.slug='liaven_apprentice';
update public.item_definitions d set equipment_set_id=s.id,updated_at=now() from public.equipment_sets s where d.slug='liaven_apprentice_robe' and s.slug='liaven_apprentice';
update public.item_definitions d set equipment_set_id=s.id,updated_at=now() from public.equipment_sets s where d.slug='liaven_apprentice_charm' and s.slug='liaven_apprentice';
update public.item_definitions d set equipment_set_id=s.id,updated_at=now() from public.equipment_sets s where d.slug='stonewatch_helm' and s.slug='stonewatch';
update public.item_definitions d set equipment_set_id=s.id,updated_at=now() from public.equipment_sets s where d.slug='stonewatch_cuirass' and s.slug='stonewatch';
update public.item_definitions d set equipment_set_id=s.id,updated_at=now() from public.equipment_sets s where d.slug='stonewatch_gauntlets' and s.slug='stonewatch';
update public.item_definitions d set equipment_set_id=s.id,updated_at=now() from public.equipment_sets s where d.slug='stonewatch_greaves' and s.slug='stonewatch';
update public.item_definitions d set equipment_set_id=s.id,updated_at=now() from public.equipment_sets s where d.slug='ash_circle_hood' and s.slug='ash_circle';
update public.item_definitions d set equipment_set_id=s.id,updated_at=now() from public.equipment_sets s where d.slug='ash_circle_robe' and s.slug='ash_circle';
update public.item_definitions d set equipment_set_id=s.id,updated_at=now() from public.equipment_sets s where d.slug='ash_circle_focus' and s.slug='ash_circle';

